### ISSUE TITLE
Federation health check complains on first startup for a couple of seconds

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/synapse-wrapper#17]
![Screen Shot 2021-11-24 at 4 46 54 PM](https://user-images.githubusercontent.com/45926711/143332073-658d1f9f-150a-4aad-b126-7ebe488718ad.png)

**Comment by chrisguida** [comment]
@BitcoinMechanic please test

**Comment by BitcoinMechanic** [comment]
Working
