### ISSUE TITLE
Refactor instructions, probably move to docs

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/synapse-wrapper#22]
All documentation should be in the docs repo, linked to in the UI when relevant.  In this case there is the special consideration of the mac app download, need to figure out a better way to handle this if it needs to be done from EOS for the purpose of decentralization.

**Comment by ProofOfKeags** [comment]
having central docs on start9.com is good but removing them from the packages is something I'd like to avoid doing if possible. The reason is that we don't want Start9 to be an ongoing dependency of usage instructions for an arbitrarily large set of services.

**Comment by kn0wmad** [comment]
Agreed, but should a service produce a webUI for instructions when there is an instructions segment of the UI?

**Comment by ProofOfKeags** [comment]
Definitely not. The instructions should be moved to the instructions tab of the package, from there we should probably remove the web UI.

**Comment by kn0wmad** [comment]
The only UX concern is that this was done in order to allow a DMG to be directly downloaded.  Not sure how this should be addressed, perhaps just by linking to the download page

**Comment by chrisguida** [comment]
Yeah the reason for making the instructions interface was so that Mac users could download the "Element Onion" installer, which would be hosted on their own box. I believe @MattDHill and @dr-bonez did this to reduce reliance on S9.

**Comment by MattDHill** [comment]
That's correct. Otherwise we would have just used the instructions tab. If there's a better way to accomplish this, then we should do it.

**Comment by kn0wmad** [comment]
Closing this for now.  Instructions refactor is forthcoming, but this will remain a special case for the time being
