### ISSUE TITLE
Synapse crashes on start up.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/synapse-wrapper#25]
`The service synapse has crashed with the following exit code: 1 Details: Traceback (most recent call last): File "/configurator.py", line 71, in main() File "/configurator.py", line 24, in main homeserver_cfg["public_baseurl"] = "http://" + os.getenv("TOR_ADDRESS") TypeError: 'NoneType' object does not support item assignment `

**Comment by BitcoinMechanic** [comment]
Not sure if duplicate. This is my migrated prod box.

**Comment by BitcoinMechanic** [comment]
Fixed - deleted empty `homeserver.yaml` and restarted service. @chrisguida summary:

`I think the configurator just doesn't handle the case where the file exists but is empty`

Not sure if this is something to worry about or not. Doesn't seem to have happened to anyone else.

**Comment by chrisguida** [comment]
Yep, will investigate, thanks.
