### ISSUE TITLE
[feat] Add synaps-admin to wrapper

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/synapse-wrapper#28]
[Synapse-admin](https://github.com/Awesome-Technologies/synapse-admin) allows you to do some basic user/room management in an easy to use UI. I believe this would be excellent addition for synapse-wrapper.
![screenshots](https://user-images.githubusercontent.com/3606313/166109189-cd6b46f6-7536-43a3-bc15-b05edf783fb8.jpg)

**Comment by ProofOfKeags** [comment]
Assigning to @MattDHill  as this is a product management question for synapse. With his approval we can schedule it for the next release of synapse.

**Comment by MattDHill** [comment]
Approved 100%. This would replace the current Synapse UI, which is just instructions. We could move these instructions to the actual "Instructions" section, but would need to remove the MacOS Element dmg download to somewhere else. Actions maybe?

**Comment by chrisguida** [comment]
@MattDHill the custom macos app is actually not needed according to @k0gen . See: https://github.com/Start9Labs/synapse-wrapper/issues/29

**Comment by k0gen** [comment]
Added in #52
