### ISSUE TITLE
Synapse Element Onion.app is not needed for macOS 

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/synapse-wrapper#29]
If you setup Tor system wide on macOS the `Element Onion.app` hosted on Synapse Instruction page is not needed.

# Install tor via brew:
`brew install tor`
`brew services start tor`

# Enable apache service:
`sudo launchctl load -w /System/Library/LaunchDaemons/org.apache.httpd.plist`

# Download proxy auto config file: 
 `sudo curl https://registry.start9labs.com/sys/proxy.pac --output /Library/WebServer/Documents/proxy.pac`

# Configure network settings:
 System Preferences > Network > Wi-Fi > Advanced… > Proxies > Automatic Proxy Configuration 
Add URL:  http://localhost/proxy.pac

<img width="780" alt="to configure" src="https://user-images.githubusercontent.com/3606313/166109374-e02f0c0a-c29b-49a2-bd51-b934542a0598.png">

**Comment by ProofOfKeags** [comment]
I'm not sure what the ask of this issue is exactly. What is "Synapse Onion.app" and do we currently specify elsewhere that it is needed for Mac?

**Comment by chrisguida** [comment]
He's referring to `Element Onion`, a macos app that we provide for download from the service's custom instructions page https://github.com/Start9Labs/synapse-wrapper/blob/master/www/ElementOnion.dmg

**Comment by k0gen** [comment]
> I'm not sure what the ask of this issue is exactly. What is "Synapse Onion.app" and do we currently specify elsewhere that it is needed for Mac?

> He's referring to Element Onion, a macos app that we provide for download from the service's custom instructions page https://github.com/Start9Labs/synapse-wrapper/blob/master/www/ElementOnion.dmg

Yes, thanks @chrisguida I have updated the issue to be less confusing

**Comment by MattDHill** [comment]
This means we no longer need the instructions UI for Synapse. Content should be moved to the actual Instructions page and the UI removed altogether.

**Comment by kn0wmad** [comment]
Ideally this would be paired with #28 imo

**Comment by chrisguida** [comment]
@kn0wmad yep, that's the plan

**Comment by k0gen** [comment]
Done in d3bd070cd9c6e110e2ddb8da08ca3cf55994fc46
