### ISSUE TITLE
Don't host "Welcome to Synapse page - instructions" on synapse address

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/synapse-wrapper#30]
If you setup your system just like described in #29 the synaspe instruction could be striped down to just pointing your [matrix] client to your .onion address and in case of macOS no `Element Onion.app` hosted inside Synapse instruction page is needed nor extra --proxy parameters. Instructions should go to synapse instance > instruction

**Comment by kn0wmad** [comment]
Linking in #28 as an ideal replacement, no idea what kind of load is required here

**Comment by chrisguida** [comment]
totally agreed, that is exactly what @k0gen suggested to me, not sure if he explicitly stated that in any of the issues

**Comment by k0gen** [comment]
Implemented in d3bd070cd9c6e110e2ddb8da08ca3cf55994fc46
