### ISSUE TITLE
[bug]: Room and profile images not displaying correctly

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/synapse-wrapper#34]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.5

### Browser

Tor Browser

### Browser Version

11.5.1

### Current Behavior

![image](https://user-images.githubusercontent.com/45926711/182729859-6e2f4b95-7ec4-4540-b01a-81e645a8ecba.png)

### Expected Behavior

.

### Steps to Reproduce

.

**Comment by chrisguida** [comment]
Pretty sure this is an issue with element, not synapse

**Comment by chrisguida** [comment]
Anyway, this isn't happening to me. Have you tried a different client?

**Comment by k0gen** [comment]
Isn't this only on TorBrowser?

**Comment by chrisguida** [comment]
@BitcoinMechanic please let me know if this is happening on other clients so we can close

**Comment by BitcoinMechanic** [comment]
Can confirm it's only Tor Browser, works fine in Firefox.
